### ISSUE TITLE
References within Richtext elements don't get resolved

### ISSUE THREAD

**Issue by KoljaTM** [e-Spirit/fsxa-api#6]
When a CMS_INPUT_DOM element is parsed into RichTextElements, DatasetReference, FS_REFERENCE or FS_INDEX elements within links don't get resolved.
Within XMLParser.createRichTextElement for links the data attribute needs to be mapped properly.
maybe something like             
data.data = await mapDataEntries(JSON.parse(data.data as string), path)

**Comment by KoljaTM** [comment]
I almost get it to work, but I get cyclic references. Is there any way to limit the depth to which references are resolved?

**Comment by KoljaTM** [comment]
Instead of registering references during parsing, I opted for a post-processing after the parse step

**Comment by tgolbs** [comment]
Hi KoljaTM,

thank you very much for your PR. We have been talking about autoloading references in RichText and didn't feel it was that important yet. 

Could you describe your use case for me?

We have to differentiate a bit here, as we try to keep the initial JSON as small as possible despite everything.

**Comment by lukeundtrug** [comment]
Hi @tgolbs,

we actually have quite a similar problem. It would be immensely helpful, if we could access mapped values for CMS_INPUT_DOM-fields directly as we basically have to do the mapping ourselves now. 
Thus, we have two individual mapping layers in our app. One that is concerned with the data types as they are returned by the api in their mapped form and unmapped data values from those fields on the other hand.
We're actually thinking about implementing our own custom mapper since a mixture of mapped and unmapped values in api responses basically means we have to do twice the amount of mapping.

**Comment by henczi-espirit** [comment]
**Internal Ticket id:** TNG-1047

**Comment by sechw** [comment]
Hi, this ticket has been resolved, the changes are available in the latest versions:

- fsxa-api@10.0.0
- fsxa-pattern-library@8.0.0
- fsxa-nuxt-module@7.0.0
- fsxa-pwa@3.4.0
