### ISSUE TITLE
QUESTION: fetching navigation for a subtree

### ISSUE THREAD

**Issue by JosefBredereck** [e-Spirit/fsxa-api#83]
Hello,

We currently have the task of changing the navigation relative to a given path. Therefore my question.
Is it possible to fetch the subtree of a navigation node via the FSXA-API?

**Example Schema:**
```
- Hidden Tree Node
--- Node 1
----- [...] Subtree elements
--- Node 2
----- [...] Subtree elements
--- Node 3
----- [...] Subtree elements
```

**Example Requirement**
The `Hiden Tree Node` has the properties `hide in navigation menu` via FirstSpirit, so it doesn't get rendered initially. After performing the method `laodNode1`, the menu should be loaded for the `Node 1` subtree. Currently, the `navigation.structure` only contains entries visible from the start, which would require additional info to load just the subtree of a specific hidden element.

Is a scenario like this possible? Can it be archived via fetchNavigation or somehow by fetchByFilter?

**Comment by JosefBredereck** [comment]
I found something in the swagger doc https://navigationservice.e-spirit.cloud/docs/api/swagger-ui/?url=/docs/api/swagger.yml#/

**Comment by henczi-espirit** [comment]
Hi Josef!
Thank you for your question.
When I remember correctly we did not implement this feature in the fsxa-api.
But as you already discovered: The feature to fetch a sub tree of a navigation is available in the backend navigation service. 
Since you closed this issue, I assume that it fits your use case.
